package example:plugin;

interface logging {
    info: func(msg: string);
    warn: func(msg: string);
    error: func(msg: string);
}

interface bindings {
    record vec3 {
        x: f64,
        y: f64,
        z: f64
    }

    record block-pos {
        x: s32,
        y: s32,
        z: s32
    }

    resource player {
        get-level: func() -> level;
        get-block-pos: func() -> block-pos;
        send-message: func(msg: text-component);
        teleport: func(x: f64, y: f64, z: f64);
    }

    resource level {
        set-block: func(position: block-pos, block: string);
    }

    variant text-component {
        plain(string),
        mini-message(string),
        json(string)
    }
}

interface events {
    use bindings.{player};

    variant event {
        tick,
        tick-player(player),
        message(message-event),
    }

    variant event-result {
        allow,
        default,
        deny
    }

    record message-event {
        message: option<string>
    }

    handle-event: func(event: event) -> event-result;
}

world plugin {
    import logging;
    export events;

    export plugin-id: func() -> string;
    export entry: func();
}
